### ISSUE TITLE
Restoration Log should record # removed for planting

### ISSUE THREAD

**Issue by cflipse** [rubyforgood/coral#82]
Record the number of coral removed for planting from a table.  These are the healthy, successful coral!

**Comment by cflipse** [comment]
Update the Restoration Activity Log Entry to include  the number of coral that have been removed for planting.

Should include database migration, as well as updates to the input form and log display

**Comment by cassiemoy** [comment]
👋 browsing through the Hacktoberfest tags; this is such a delightful project - may I try this?

**Comment by cflipse** [comment]
Go for it!
